### PR TITLE
Added the option for a user to track the location of a locomotive 

### PR DESCRIPTION
**Pull request by 12johnsonf**
whem it is moving on a layout.

This means that a use could implement a signalling system and be able to automagically slow down a train near a signal, or other useful things.

I will for sure be using this in my future layout.

### CODE REVIEW

**Comment by 12johnsonf** [comment]
I don't know why the build failed... can you offer insight?

**Comment by hsanjuan** [comment]
Hey, can you give more details of how carrying a Block string within the Locomotive struct helps with that implementation? Perhaps it's something to carry in a Locomotive wrapper.

The reason why I ask is that Locomotive == DCC Device and the information it carries is supposed to be information that can be encoded and transmitted to DCC devices following the specs.

Other than that, the changed line is not correctly formatted. And the tests are failing because of failing coverage submission from your account (so ignore it, it's not a real problem).

**Comment by 12johnsonf** [comment]
I know it represents a DCC device, but imagine that a user is trying to create a signalling system to track the locomotive's location, and they wanted to keep track of it on the layout in their program. The addition of this block string means that this can be stored with the communication, so say you could find the locomotive that is within a block and then modify the speed (to stop it, for example)

**Comment by hsanjuan** [comment]
@12johnsonf why not doing something like:

```go
type TrackedLoco struct {
    L dcc.Locomotive
    Block string
    ....
}
```

It seems very arbitrary to include a non DCC-related field in `Locomotive` to track some information which does not travel encoded on packets on the tracks (and may need additional fields, or different types depending on the implementation). I won't be merging this, sorry.

**Pull request closed without merging**
